/*
Copyright © 2021 NAME HERE <EMAIL ADDRESS>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package cmd

import (
	"fmt"
	"os"
	"path"

	"github.com/spf13/cobra"

	homedir "github.com/mitchellh/go-homedir"
	"github.com/spf13/viper"
)

var cfgFile string
var hlfdPath string

// Root flags
type RootFlags struct {
	HlfdPath string
}

var rootFlags RootFlags

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "hlfd",
	Short: "A brief description of your application",
	Long: `A longer description that spans multiple lines and likely contains
examples and usage of using your application. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.`,
	// Uncomment the following line if your bare application
	// has an action associated with it:
	// Run: func(cmd *cobra.Command, args []string) { },
	TraverseChildren: true,
	Version:          "v0.0.1",
	// PersistentPreRun: func(cmd *cobra.Command, args []string) {
	// 	fmt.Println("persistentprerun")
	// },
	// PersistentPostRun: func(cmd *cobra.Command, args []string) {
	// 	fmt.Println("persistentpostrun")
	// },
	// PreRun: func(cmd *cobra.Command, args []string) {
	// 	// Initialize hlfd-path
	// 	initHlfdPath()
	// },
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	cobra.CheckErr(rootCmd.Execute())
}

func init() {
	cobra.OnInitialize(initConfig)

	// Here you will define your flags and configuration settings.
	// Cobra supports persistent flags, which, if defined here,
	// will be global for your application.
	// caCmd.PersistentFlags().StringVarP(&rootFlags.HlfdPath, "hlfd-path", "", "", "Files generated by this tool will be stored in this path under hlfd folder")

	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.hlfd.yaml)")

	// Cobra also supports local flags, which will only run
	// when this action is called directly.
	rootCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")

	// Initialize hlfd-path
	initHlfdPath()
}

// initConfig reads in config file and ENV variables if set.
func initConfig() {
	if cfgFile != "" {
		// Use config file from the flag.
		viper.SetConfigFile(cfgFile)
	} else {
		// Find home directory.
		home, err := homedir.Dir()
		cobra.CheckErr(err)

		// Search config in home directory with name ".hlfd" (without extension).
		viper.AddConfigPath(home)
		viper.SetConfigName(".hlfd")
	}

	viper.AutomaticEnv() // read in environment variables that match

	// If a config file is found, read it in.
	if err := viper.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", viper.ConfigFileUsed())
	}
}

func initHlfdPath() {
	// Find home directory.
	home, err := homedir.Dir()
	cobra.CheckErr(err)
	fullPath := path.Join(home, ".hlfd")
	err = os.Mkdir(fullPath, 0700)
	checkOtherThanFileExistsError(err)
	hlfdPath = fullPath
}
